//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Libs.rc
//
#define IDC_CAPTION                     101
#define IDC_TITLE                       102
#define IDC_XAXIS                       103
#define IDC_YAXIS                       104
#define IDC_SHOWHORZ                    105
#define IDC_SHOWVERT                    106
#define IDC_GROOVED                     107
#define IDC_RAISED                      108
#define IDC_SUNKEN                      109
#define IDC_LINE                        110
#define IDC_LINELABEL                   111
#define IDC_SCALEMIN                    112
#define IDC_LINECOLOR                   113
#define IDC_LINESTYLE                   114
#define IDC_SCALEMAX                    115
#define IDC_LINEWIDTH                   116
#define IDC_AUTOSCALE                   117
#define IDC_MARKER                      118
#define IDC_MARKERINCR                  119
#define IDC_SHOWLINE                    120
#define IDC_SHOWMARKER                  121
#define IDC_TICMAJOR                    122
#define IDC_MARKERINCR2                 122
#define IDC_LEGENDHEIGHT                122
#define IDC_TICMINOR                    123
#define IDC_SMOOTH                      123
#define IDC_AUTOINCR                    124
#define IDC_LEGENDHEIGHT2               124
#define IDC_TENSION                     124
#define IDC_TICDECIMALS                 125
#define IDC_GLOBAL                      126
#define IDC_LOCAL                       127
#define IDC_TICMAJORLABEL               128
#define IDC_TICMINORLABEL               129
#define IDC_SCALEMINLABEL               130
#define IDC_SCALEMAXLABEL               131
#define IDC_AXIS                        132
#define IDC_LINEFONT                    133
#define IDD_S3D_DATA_SET_PROPS          136
#define IDD_MAPLAYERPROPS               137
#define IDC_LIB_LAYER                   138
#define IDC_LIB_QUERY                   170
#define IDC_LIB_ADD                     177
#define IDC_LIB_DESCRIPTION             178
#define IDC_LIB_AND                     186
#define IDC_LIB_OR                      187
#define IDC_LIB_CLEARPREV               190
#define IDD_LIB_QUERY                   212
#define IDC_DATA_SET_COMBO              1000
#define IDC_POINT_SIZE_COMBO            1001
#define IDC_POINT_TYPE_COMBO            1002
#define IDC_POINT_SIZE_COMBO2           1003
#define IDC_LINE_SIZE_COMBO             1003
#define IDC_COLOR_STATIC                1004
#define IDC_COLOR_STATIC_LINES          1005
#define IDC_PREVIEW_STATIC              1006
#define IDC_LFILE                       1007
#define IDC_SET_COLOR_BUTTON            1008
#define IDC_SET_COLOR_BUTTON_LINES      1009
#define IDC_UPDATEPLOT                  1010
#define IDC_LTYPE                       1011
#define IDC_FEATURES                    1012
#define IDC_SHOWOUTLINES                1013
#define IDC_INTENSITY                   1014
#define IDC_INTENSITYTEXT               1015
#define IDC_LIGHTER                     1016
#define IDC_DARKER                      1017
#define IDC_VISIBLE                     1062
#define IDC_OUTLINECOLOR                1089
#define IDC_HATCHCOLOR                  1092
#define IDC_LIB_FIELDS                  1127
#define IDC_OPS                         1128
#define IDC_LIB_VALUES                  1129
#define IDC_LIB_HATCHPATTERN            1161
#define IDD_PLOTSETUP                   2001
#define IDD_PLOTAXES                    2002
#define IDD_PLOTLINES                   2003
#define IDC_FONTCAPTION                 2006
#define IDC_FONTTITLE                   2007
#define IDC_FONTXAXIS                   2008
#define IDC_FONTYAXIS                   2009
#define IDC_VARWIDTH                    2012
#define IDC_LEDITFIELDINFO              2013
#define IDC_LWIDTH                      2014
#define IDC_LSPIN1                      2016
#define IDD_MAPLABELS                   2017
#define IDC_LLAYERS                     2017
#define IDC_SHOWLABELS                  2018
#define IDC_LABEL_FIELDS                2019
#define IDD_NAME                        2019
#define IDC_FONTSAMPLE                  2020
#define IDD_CELLPROPERTIES              2020
#define IDC_SETFONT                     2021
#define IDD_ERRORREPORT                 2021
#define IDD_LIBS_QUERY                  2022
#define IDD_LIBS_SORTCOLS               2023
#define IDC_EDITLABELINFO               2024
#define IDC_LIB_FIELDCOMBO              2026
#define IDC_LIB_ADDFIELD                2027
#define IDC_LIB_REMOVEFIELD             2028
#define IDC_LIB_TYPE                    2029
#define IDC_LIB_WIDTH                   2030
#define IDC_LIB_DECIMALS                2031
#define IDC_LIB_REORDERCOLS             2032
#define IDC_EXTENTS2                    2033
#define IDC_LIB_NAME                    2034
#define IDC_LIB_FLASHCELL               2035
#define IDC_LIB_NEXTCELL                2036
#define IDC_LIB_PREVCELL                2037
#define IDC_LIB_GRID_FRAME              2038
#define IDC_TRANSPARENCY                2040
#define IDC_TRANSPARENCY_VALUE          2041
#define ID_LIB_CELLPROPERTIES           2042
#define ID_LIB_SHOWSAMEATTRIBUTE        2043
#define ID_LIB_SHOWPOLYGONVERTICES      2044
#define ID_LIB_ZOOMTOPOLY               2045
#define ID_LIB_RECLASSIFYDATA           2046
#define IDC_LIB_MSG                     2047
#define IDC_LIB_OUTPUT                  2048
#define IDC_LIB_NOMSGS                  2049
#define IDC_TENSIONLABEL                2052
#define IDC_LIB_TOTALAREA               2054
#define IDC_LIB_AVERAGEAREA             2055
#define IDC_LIB_AREARANGE               2056
#define IDC_LIB_AVERAGEAREA2            2056

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2024
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2057
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
